# Generated by Django 3.0.5 on 2020-04-16 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0018_auto_20200416_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='author',
            field=models.ForeignKey(default='dahko37', on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.Conversation', to_field='name'),
        ),
    ]
